# Kaggle Competition - Predicting Irrigation Need

**Name:** Christine Wu
**Date:** 04/13/26

## Submission Instructions: 
Submit the URL to your GitHub repository Kaggle Homework document (see below for details).

## Week 1:

### 1. Register for the Kaggle playground series competition S6E4. This competition started April 1st and will run until April 30th. It will be part of the homework for the next several weeks. You should compete solo for the homework assignments.

https://www.kaggle.com/competitions/playground-series-s6e4/leaderboard

### 2. Create a dedicated repository (or a clear sub-folder) in your GitHub for the Kaggle competition. This is a 3-week project; organize it so you can add new notebooks as needed without clutter.

URL Link to Repo Subfolder: https://github.com/imcwu/advancedmlrepo/tree/main/kagglecomp1

### 3. Set up a single Jupyter Notebook or a clean Markdown file in your Kaggle repo/folder titled "Kaggle Homework- [Your Name]-[Kaggle user name]". Use this to answer questions for each homework related to the competition, including URLs to Kaggle notebooks/discussions and to your own modeling notebooks (in your repo or posted on Kaggle).

Done (it's this notebook)

### 4. Find and upvote 3-4 notebooks or discussion posts that you find particularly insightful or you could realistically apply in your own modeling. Provide the URLs in your Homework document. Posting on discussion boards in Kaggle is a great way to get some exposure, but is not required.

1. https://www.kaggle.com/code/utaazu/0-979-cv-single-lgbm-pairwise-te-bias-tuning?scriptVersionId=308878125

+ I chose this post because it focuses on how to build a clean baseline before starting feature engineering, and it talks about to how to handle class imbalance. This will help improve my approach because it taught me the strategy is to start simple and then iterate my model over time.

2. https://www.kaggle.com/code/komilparmar/ps-s6e4-deep-exploratory-data-analysis

+ I chose this post because it explains how to use a end-to-end pipeline, and shows the process of how to use a strong baseline model called LightGBM. This will help improve my approach because I can also try out this model.

3. https://www.kaggle.com/code/zaouiyassine/s6e4-baseline-submissions

+ I chose this post because it is very detailed in explaining how to conduct EDA for the competition. It covers not only how to deal with class imbalance, but it also explains the training vs testing shift. This will help improve my approch because it helped me better understand the distribution of the data in general.

### 5. Create an EDA notebook for the competition. Do your initial EDA in that notebook and provide the URL in your Homework document. What insights did you gain? Is there a feature you think is especially important? Any potential issues? Did you try anything new that you learned from Kaggle or other sources? Consider posting a public EDA notebook on Kaggle.

URL Link to the EDA notebook: https://github.com/imcwu/advancedmlrepo/blob/main/kagglecomp1/IrrigationEDA.ipynb

The dataset is very clean and well-structured, containing 630,000 observations and 21 features with no missing values. There are 12 numerical and 9 categorical variables. The dataset is also extremely large, and most variables have minimal skew and flat distributions, so there are no extreme outliers.

The target variable, Irrigation_Need is the most important variable, since it's the variable we're predicting. It is limited in number of categories (3), and being able to distinguish these categories from each other will be our final goal. Additionally, categorical variables such as Region and Mulching_Used sound like they will be important because they are agricultural conditions that signficantly influence real-life irrigation. Finally, numerical variables with low skew will be strong influencers of the irrigation need, since they provide stable signals.

A potential issue could be that the target variable only has 3 categories, which could cause class imbalance based on how the observations are distributed across these classes. Another issue could be that the large size of the dataset could make training less efficient and take longer.

I did not try anything new as I just used SweetViz for basic EDA of the dataset.

### 6. Use two distinct modeling approaches, one bagging and one boosting. You may build other models, but the goal for the homework is to compare bagging and boosting approaches. You must submit at least one boosting and one bagging set of predictions to Kaggle (gets your submission workflow established). Consider exploring models we didn't cover in class. Make sure you are using cross-validation or another validation metric to improve your modeling. Do some tuning but don't spend hours and hours on it at this stage. Again, consider posting a public notebook on Kaggle (many people post only one or two notebooks out of many that they create).

### 7. In your Kaggle Homework document provide:

#### 1. URLs for the resources you upvoted on the competition site.  Discuss why you chose each--how will it help you improve your approach?

Done (See above)

#### 2. Links to your EDA notebook and bagging and boosting notebook(s).

URL Link to the EDA notebook: https://github.com/imcwu/advancedmlrepo/blob/main/kagglecomp1/IrrigationEDA.ipynb

URL Link to the Bagging Notebook: https://github.com/imcwu/advancedmlrepo/blob/main/kagglecomp1/BaggingModel.ipynb

URL Link to the Boosting Notebook: https://github.com/imcwu/advancedmlrepo/blob/main/kagglecomp1/BoostingModel.ipynb

#### 3. Discuss your modeling approaches. What did you try? What worked well? What didn't work well? Were model improvements meaningful or small? Make sure to use performance metrics in your discussion. Also provide leaderboard scores for the models. A table might be useful for organizing the metrics and leaderboard scores.

I implemented two models: a bagging model using Random Forest and a boosting model using HistGradientBoosting. Both models used preprocessing to handle numeric and categorical variables and were evaluated using Stratified K-Fold cross-validation with 3 folds. For the Random Forest model, I used one-hot encoding for categorical variables and tuned parameters such as number of trees and depth. For the boosting model, I used integer encoding for categorical variables and tuned parameters such as learning rate and number of iterations.

Both models performed well and achieved high accuracy. The Random Forest model achieved a Kaggle score of 0.96034 and ranked 1161 on the leaderboard. The boosting model achieved a score of 0.95923 and ranked 1361. The Random Forest model performed slightly better than the boosting model. The difference in accuracy was small at about 0.0011, but it resulted in a noticeable difference in leaderboard ranking.

The Random Forest model likely performed better because of one-hot encoding, which allowed it to better capture categorical relationships. The boosting model was faster and more memory efficient but performed slightly worse. Limited hyperparameter tuning due to computational constraints may have prevented further improvements.

In [1]:
import pandas as pd

# Create results table
results = pd.DataFrame({
    "Model": ["Random Forest (Bagging)", "HistGradientBoosting (Boosting)"],
    "CV Accuracy (approx)": ["~0.96", "~0.95–0.96"],
    "Kaggle Score": [0.96034, 0.95923],
    "Leaderboard Rank": [1161, 1361]
})

print(results)

                             Model CV Accuracy (approx)  Kaggle Score  \
0          Random Forest (Bagging)                ~0.96       0.96034   
1  HistGradientBoosting (Boosting)           ~0.95–0.96       0.95923   

   Leaderboard Rank  
0              1161  
1              1361  


#### 4. How did boosting versus bagging compare for your work?

My bagging model was faster to run and more accurate as it achieved a score of 0.96034 versus the score that the boosting model got (0.95923). Both models surprisingly performed super well. But overall, my bagging model was better.

### 8. What is your "phase 2" plan to improve your model performance? Note that although the leaderboard is fun to watch, you are not graded on it (and a shake up often occurs at the end!)

My phase 2 plan is to improve my model performance by further tuning hyperparameters like tree depth, learning rate, and number of estimators, trying more boosting models like XGBoost or CatBoost to compare to Random Forest, and to also check for class imbalance and test class weights to focus on the features that contribute most to prediction accuracy.

## Week 2 Update: Bagging and Boosting Model Comparison

For this week's work, I expanded my ensemble modeling by comparing both bagging and boosting methods across separate notebooks. I used balanced accuracy as my main validation metric because it matches the Kaggle competition scoring metric.

The bagging models I compared were:
- Random Forest
- Extra Trees

The boosting models I compared were:
- HistGradientBoosting
- XGBoost
- CatBoost

I also tested multiple hyperparameter settings for the additional boosting models to see whether changing the inputs would meaningfully affect performance.

In [5]:
import pandas as pd

week2_results = pd.DataFrame({
    "Model Type": [
        "Bagging",
        "Bagging",
        "Boosting",
        "Boosting",
        "Boosting"
    ],
    "Model": [
        "Random Forest",
        "Extra Trees",
        "HistGradientBoosting",
        "XGBoost",
        "CatBoost"
    ],
    "CV Balanced Accuracy": [
        "N/A",
        0.88713,
        0.98429,
        0.95909,
        0.95998
    ],
    "Kaggle Score": [
        0.96034,
        0.88387,
        0.95923,
        0.95624,
        0.95733
    ]
})

week2_results

,Model Type,Model,CV Balanced Accuracy,Kaggle Score
0,Bagging,Random Forest,N/A,0.96034
1,Bagging,Extra Trees,0.88713,0.88387
2,Boosting,HistGradientBoosting,0.98429,0.95923
3,Boosting,XGBoost,0.95909,0.95624
4,Boosting,CatBoost,0.95998,0.95733


## Discussion of Modeling Approaches

For this week's task, I compared both bagging and boosting ensemble methods using separate notebooks. In the bagging notebook, I compared Random Forest and Extra Trees. In the boosting notebook, I compared HistGradientBoosting, XGBoost, and CatBoost.

Among the bagging models, Random Forest clearly performed much better than Extra Trees. The Extra Trees model had a cross-validation balanced accuracy of 0.88713 and a Kaggle public score of 0.88387, which were both much lower than the Random Forest results. This showed that the additional randomness in Extra Trees did not help on this dataset.

Among the boosting models, HistGradientBoosting performed best on the leaderboard with a public score of 0.95923. CatBoost was next with 0.95733, and XGBoost followed with 0.95624. I also tested two hyperparameter settings each for CatBoost and XGBoost. In both cases, the second parameter set performed a little better than the first, which showed that changing hyperparameters did affect the results.

Overall, the model improvements among the boosting methods were fairly small. CatBoost and XGBoost were competitive, but neither one beat HistGradientBoosting. The biggest difference I found was between the bagging models, where Random Forest strongly outperformed Extra Trees.

My main takeaway is that ensemble models were very effective for this competition, but some were clearly a better fit than others. Random Forest was the best bagging model, and HistGradientBoosting was the best boosting model.

## Comparison of Models

Comparing all five models together, Random Forest gave me the best overall Kaggle score at 0.96034. HistGradientBoosting was a close second at 0.95923. CatBoost and XGBoost were slightly lower at 0.95733 and 0.95624, while Extra Trees was far behind at 0.88387.

This means that the strongest models in my work were Random Forest and HistGradientBoosting. CatBoost and XGBoost still performed reasonably well and helped me understand the effects of hyperparameter tuning, but their improvements were small. Extra Trees was the weakest model and showed that not every tree ensemble is equally effective for this dataset.

Overall, my results suggest that ensemble methods are strong for tabular prediction problems, but the specific algorithm and its hyperparameter settings still matter.

In [7]:
best_models_summary = pd.DataFrame({
    "Best Bagging Model": ["Random Forest"],
    "Bagging Kaggle Score": [0.96034],
    "Best Boosting Model": ["HistGradientBoosting"],
    "Boosting Kaggle Score": [0.95923],
    "Best Overall Model": ["Random Forest"],
    "Best Overall Kaggle Score": [0.96034]
})

best_models_summary

,Best Bagging Model,Bagging Kaggle Score,Best Boosting Model,Boosting Kaggle Score,Best Overall Model,Best Overall Kaggle Score
0,Random Forest,0.96034,HistGradientBoosting,0.95923,Random Forest,0.96034
